apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.hyperfleetAdapter1Chart.applicationName }}-task
  namespace: {{ .Values.hyperfleetAdapter1Chart.targetNamespace }}
  labels:
    app.kubernetes.io/name: {{ .Values.hyperfleetAdapter1Chart.applicationName }}
    app.kubernetes.io/component: adapter-task-config
data:
  task-config.yaml: |
{{ .Files.Get "adapter-task-config.yaml" | nindent 4 }}
  manifestwork.yaml: |
{{ .Files.Get "manifestwork.yaml" | nindent 4 }}
