adapter:
  name: adapter1
  version: "0.2.1"
debug_config: true
log:
  level: debug
clients:
  hyperfleet_api:
    base_url: http://hyperfleet-api:8000
    version: v1
    timeout: 2s
    retry_attempts: 3
    retry_backoff: exponential
  broker:
    subscription_id: subscription
    topic: clusters
  maestro:
    grpc_server_address: "maestro-grpc.maestro-server.svc.cluster.local:8090"
    http_server_address: "http://maestro-http.maestro-server.svc.cluster.local:8080"
    source_id: "hyperfleet-adapter"
    client_id: "hyperfleet-adapter-client"
    insecure: true
    auth:
      type: "none"
