apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alert-bridge-sns-config
  namespace: {{ index .Values "alert-bridge-chart" "targetNamespace" }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-parameter-store
    kind: ClusterSecretStore
  target:
    name: alert-bridge-sns-config
  data:
    - secretKey: sns-topic-arn
      remoteRef:
        key: /{{ .Values.global.cluster_name }}/alerting/sns-topic-arn
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
