apiVersion: v1
kind: Service
metadata:
  name: sigv4-proxy
  labels:
    app.kubernetes.io/name: sigv4-proxy
    app.kubernetes.io/component: metrics-proxy
spec:
  selector:
    app.kubernetes.io/name: sigv4-proxy
  ports:
    - name: proxy
      port: 8005
      targetPort: 8005
      protocol: TCP
