apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ include "thanos-operator.namespace" . }}
  labels:
    {{- include "thanos-operator.labels" . | nindent 4 }}
  annotations:
    {{- include "thanos-operator.annotations" . | nindent 4 }}
    {{- if .Values.global.aws_account_id }}
    {{- $partition := ternary "aws-us-gov" "aws" (hasPrefix "us-gov-" .Values.global.aws_region) }}
    eks.amazonaws.com/role-arn: {{ printf "arn:%s:iam::%s:role/%s-thanos" $partition .Values.global.aws_account_id .Values.global.cluster_name | quote }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
