# ArgoCD Application configuration
hyperfleetAdapter0Chart:
  applicationName: hyperfleet-adapter0
  namespace: argocd
  targetNamespace: hyperfleet-system
  project: default
  source:
    repoURL: https://github.com/openshift-hyperfleet/hyperfleet-adapter
    path: charts
    targetRevision: v0.1.1

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions: []

secretProvider:
  name: hyperfleet-adapter0-secrets
