import logging
import os

import boto3

log = logging.getLogger(__name__)


CENTRAL_REGION = "us-east-1"

# Standard profile names — must match ci/setup-aws-profiles.sh and the
# container configs generated by scripts/dev/ephemeral-env.sh / int-env.sh.
PROFILE_CENTRAL = "rrp-central"
PROFILE_RC = "rrp-rc"
PROFILE_MC = "rrp-mc"

_PREFIX_TO_PROFILE = {
    "regional": PROFILE_RC,
    "management": PROFILE_MC,
}


class AWSCredentials:
    """Manages AWS sessions via named profiles.

    Expects an AWS config file (pointed to by AWS_CONFIG_FILE) with profiles:
      - rrp-central  — central account (pipeline-provisioner, SSM parameters)
      - rrp-rc       — regional account
      - rrp-mc       — management account

    In CI, these profiles are generated by ``ci/setup-aws-profiles.sh`` from
    Prow-mounted credential files.  For local dev, they are generated by
    ``scripts/dev/ephemeral-env.sh`` with resolved SAML credentials.

    Two sessions are maintained:
      - ``session`` targets the central region (us-east-1).
      - ``target_session`` targets the region where RC/MC pipelines run.

    Use ``subprocess_env`` when spawning child processes that need central
    account AWS access (terraform, bootstrap scripts).
    """

    def __init__(self, target_region: str = "us-east-1"):
        self.central_region = CENTRAL_REGION
        self.target_region = target_region
        self.central_account_id = None
        self.session: boto3.Session | None = None
        self.target_session: boto3.Session | None = None
        self.subprocess_env: dict[str, str] = {}

    @staticmethod
    def _forward_config_env(env: dict[str, str]) -> None:
        """Copy AWS config/credentials file paths into a subprocess env dict."""
        for key in ("AWS_CONFIG_FILE", "AWS_SHARED_CREDENTIALS_FILE"):
            if os.environ.get(key):
                env[key] = os.environ[key]

    def setup_central_account(self):
        """Set up central account access via the rrp-central profile."""
        log.info("Setting up central account access")

        self.session = boto3.Session(
            profile_name=PROFILE_CENTRAL,
            region_name=self.central_region,
        )

        self.target_session = boto3.Session(
            profile_name=PROFILE_CENTRAL,
            region_name=self.target_region,
        )

        self.subprocess_env = {
            "AWS_PROFILE": PROFILE_CENTRAL,
            "AWS_DEFAULT_REGION": self.central_region,
            "AWS_REGION": self.central_region,
        }
        self._forward_config_env(self.subprocess_env)

        identity = self.session.client("sts").get_caller_identity()
        self.central_account_id = identity["Account"]
        log.info("Access set up to Central CI Account ID: %s", self.central_account_id)

    def _profile_for(self, prefix: str) -> str:
        """Map an account prefix to a profile name."""
        profile = _PREFIX_TO_PROFILE.get(prefix)
        if not profile:
            raise ValueError(f"Unknown account prefix: {prefix!r} (expected 'regional' or 'management')")
        return profile

    def get_target_account_id(self, prefix: str) -> str:
        """Get the AWS account ID for a target account.

        Args:
            prefix: Account prefix ('regional' or 'management').

        Returns:
            The 12-digit AWS account ID.
        """
        profile = self._profile_for(prefix)
        session = boto3.Session(profile_name=profile)
        return session.client("sts").get_caller_identity()["Account"]

    def target_subprocess_env(self, prefix: str) -> dict[str, str]:
        """Build a subprocess environment dict for a target account.

        Args:
            prefix: Account prefix ('regional' or 'management').

        Returns:
            Dict with AWS_PROFILE, AWS_CONFIG_FILE, and region variables.
        """
        profile = self._profile_for(prefix)
        env = {
            "AWS_PROFILE": profile,
            "AWS_DEFAULT_REGION": self.target_region,
            "AWS_REGION": self.target_region,
        }
        self._forward_config_env(env)
        return env

    def setup_target_account_trust(self, prefix: str):
        """Set up trust policy in a sub-account so the central account can assume roles.

        Args:
            prefix: Account prefix ('regional' or 'management').
        """
        import json

        if not self.central_account_id:
            raise RuntimeError(
                "central_account_id is not set — setup_central_account() must be called first"
            )

        log.info("Temporary Setup: Updating trust policy in %s account", prefix)

        role_name = "OrganizationAccountAccessRole"
        principal = f"arn:aws:iam::{self.central_account_id}:root"

        profile = self._profile_for(prefix)
        session = boto3.Session(profile_name=profile)
        iam = session.client("iam")

        role = iam.get_role(RoleName=role_name)
        existing_policy = role["Role"]["AssumeRolePolicyDocument"]

        for stmt in existing_policy.get("Statement", []):
            aws_principals = stmt.get("Principal", {}).get("AWS", [])
            if isinstance(aws_principals, str):
                aws_principals = [aws_principals]
            if (
                stmt.get("Effect") == "Allow"
                and stmt.get("Action") == "sts:AssumeRole"
                and principal in aws_principals
            ):
                log.info("Trust for %s already exists in %s account, skipping.", principal, prefix)
                return

        existing_policy["Statement"].append(
            {
                "Effect": "Allow",
                "Principal": {"AWS": principal},
                "Action": "sts:AssumeRole",
            }
        )

        iam.update_assume_role_policy(
            RoleName=role_name,
            PolicyDocument=json.dumps(existing_policy),
        )
        log.info("Updated trust on %s in %s account to allow assumeRole from %s.", role_name, prefix, principal)
