apiVersion: v2
name: thanos-operator
description: A Helm chart with thanos-operator as subchart
type: application
version: 0.1.0

dependencies:
  - name: thanos-operator
    version: 0.1.0
    repository: oci://quay.io/bsmit/rhobs-thanos-operator-chart
